INSERT INTO vrp.USERS (ID_PK, HASHED_PASSWORD, PHONE_NUMBER, EMAIL,
                       CREATED, ACCESS_FAILED_COUNT, LOCK_EXPIRED, SUSPENDED, DELETED, FULL_NAME)
VALUES (-1, E '73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8', '+989129999999',
        E 'book.local@gmail.com', '2019-08-05 11:11:06.552000', 0,
        NULL, FALSE, NULL, 'ادمین اصلی');

INSERT INTO vrp.SECURITY_ROLE (ID_PK, CATEGORY, NAME, DELETED, SHOW, TYPE)
VALUES (-1, NULL, E 'ادمین اصلی', FALSE, FALSE, 0);

INSERT INTO vrp.USER_SESSION(ID_PK, AGENT, CREATED, IP, OS, USER_ID_FK)
VALUES (-1, 'Mozilla', '2020-09-06 10:56:34.086', '91.92.205.199', 'Unix', -1);

INSERT INTO vrp.SECURITY_REALM (ID_PK, DELETED, NAME)
VALUES (-1, FALSE, 'realm');

INSERT INTO vrp.SECURITY_USER_ROLE_REALM (ID_PK, REALM_ID_FK, ROLE_ID_FK, USER_ID_FK)
VALUES (-1, -1, -1, -1);

DELETE
FROM vrp.SECURITY_ROLE_PERMISSION
WHERE ROLE_ID_FK = -1;

INSERT INTO vrp.SECURITY_ROLE_PERMISSION (ROLE_ID_FK, PERMISSION_ID_FK)
SELECT -1, PERMISSION.ID_PK
FROM vrp.SECURITY_PERMISSION PERMISSION
WHERE PERMISSION.NODE_TYPE NOT IN (1, 5)
  AND PERMISSION.TYPE IN ('ADMIN', 'MEMBER');