INSERT INTO USERS (ID_PK, HASHED_PASSWORD, PHONE_NUMBER, EMAIL,
                   CREATED, ACCESS_FAILED_COUNT, LOCK_EXPIRED, SUSPENDED, DELETED, USERNAME)
VALUES (-1, '73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8', '+989129999999',
        'book.local@gmail.com', NOW()::TIMESTAMP, 0,
        NULL, FALSE, NULL, 'ادمین اصلی');

INSERT INTO SECURITY_ROLE (ID_PK, NAME, SHOW, TYPE)
VALUES (-1, 'ادمین اصلی', FALSE, 0);

INSERT INTO SECURITY_ROLE (ID_PK, NAME, SHOW, TYPE)
VALUES (-2,  'ADMIN', TRUE, 0);

INSERT INTO SECURITY_ROLE (ID_PK, NAME, SHOW, TYPE)
VALUES (-3,  'MEMBER', TRUE, 0);

INSERT INTO USER_SESSION(ID_PK, AGENT, CREATED, IP, OS, USER_ID_FK)
VALUES (-1, 'Mozilla', '2020-09-06 10:56:34.086', '91.92.205.199', 'Unix', -1);

INSERT INTO SECURITY_REALM (ID_PK, NAME)
VALUES (-1, 'realm');

INSERT INTO SECURITY_USER_ROLE_REALM (ID_PK, REALM_ID_FK, ROLE_ID_FK, USER_ID_FK)
VALUES (-1, -1, -1, -1);

DELETE
FROM SECURITY_ROLE_PERMISSION
WHERE ROLE_ID_FK IN (-1, -2, -3);

INSERT INTO SECURITY_ROLE_PERMISSION (ROLE_ID_FK, PERMISSION_ID_FK)
SELECT -1, PERMISSION.ID_PK
FROM SECURITY_PERMISSION PERMISSION
WHERE PERMISSION.NODE_TYPE NOT IN (1, 5)
  AND PERMISSION.TYPE IN ('ADMIN', 'MEMBER');

INSERT INTO SECURITY_ROLE_PERMISSION (ROLE_ID_FK, PERMISSION_ID_FK)
SELECT -2, PERMISSION.ID_PK
FROM SECURITY_PERMISSION PERMISSION
WHERE PERMISSION.NODE_TYPE NOT IN (1, 5)
  AND PERMISSION.TYPE IN ('ADMIN');

INSERT INTO SECURITY_ROLE_PERMISSION (ROLE_ID_FK, PERMISSION_ID_FK)
SELECT -3, PERMISSION.ID_PK
FROM SECURITY_PERMISSION PERMISSION
WHERE PERMISSION.NODE_TYPE NOT IN (1, 5)
  AND PERMISSION.TYPE IN ('MEMBER');